CREATE DATABASE IF NOT EXISTS restore CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE restore;

CREATE TABLE IF NOT EXISTS Kullanicilar (
    KullaniciID INT AUTO_INCREMENT PRIMARY KEY,
    KullaniciAd VARCHAR(150) NOT NULL,
    KullaniciEmail VARCHAR(255) NOT NULL UNIQUE,
    Sifre VARCHAR(255) NOT NULL,
    Telefon VARCHAR(30) NULL
);

CREATE TABLE IF NOT EXISTS Adresler (
    AdresID INT AUTO_INCREMENT PRIMARY KEY,
    KullaniciID INT NOT NULL,
    Baslik VARCHAR(100) NOT NULL,
    AdresDetay VARCHAR(500) NOT NULL,
    Sehir VARCHAR(100) NOT NULL,
    Ilce VARCHAR(100) NOT NULL,
    Varsayilan TINYINT(1) NOT NULL DEFAULT 0,
    CONSTRAINT FK_Adresler_Kullanicilar FOREIGN KEY (KullaniciID) REFERENCES Kullanicilar(KullaniciID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Siparisler (
    SiparisID INT AUTO_INCREMENT PRIMARY KEY,
    KullaniciID INT NOT NULL,
    AdresID INT NOT NULL,
    ToplamFiyat DECIMAL(10,2) NOT NULL,
    Tarih DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_Siparisler_Kullanicilar FOREIGN KEY (KullaniciID) REFERENCES Kullanicilar(KullaniciID) ON DELETE CASCADE,
    CONSTRAINT FK_Siparisler_Adresler FOREIGN KEY (AdresID) REFERENCES Adresler(AdresID) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS SiparisDetay (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    SiparisID INT NOT NULL,
    UrunAdi VARCHAR(255) NOT NULL,
    Fiyat DECIMAL(10,2) NOT NULL,
    CONSTRAINT FK_SiparisDetay_Siparisler FOREIGN KEY (SiparisID) REFERENCES Siparisler(SiparisID) ON DELETE CASCADE
);
